### ISSUE TITLE
Period is a final class

### ISSUE THREAD

**Issue by manubing** [thephpleague/period#12]
Hi,

Just wondering, why Period is a final class?

Thanks

**Comment by manubing** [comment]
There is a mention on this in #9, but without a direct response on this subject.

**Comment by nyamsprod** [comment]
Period is a [immutable value object](http://martinfowler.com/bliki/ValueObject.html). To respect this contract you need to make sure the API you are exposing won't be temper with by third party code. The best way to ensure code stability is to make the class final so that it is still open for extension but close for inheritance. To quote [Mathias Verraes](http://verraes.net/2014/05/final-classes-in-php/)

> It’s important to understand that “Open for extension”, does not mean “Open for inheritance”. Composition, strategies, callbacks, plugins, event listeners, … are all valid ways to extend without inheritance. And usually, they are much preferred to inheritance – hence the adage “favour composition over inheritance”. 

Hope this will clarify the use of the final keyword.

**Comment by manubing** [comment]
yes, thanks!
