### ISSUE TITLE
Upgrade from 4.11 to 4.12 getDatePeriod returns DateTimeImmutable instead of Datepoints?

### ISSUE THREAD

**Issue by arendjantetteroo** [thephpleague/period#126]
### Bug Report

| Information | Description |
|--------------|---------|
| Version |  4.11
| PHP version |  8.0.16
| OS Platform |  Ubuntu 20.04 LTS

#### Summary

I just upgraded to 4.12 from 4.11 and got TypeErrors afterwards. 

Uncaught TypeError: TactiPlan\\Contracts\\ContractHours\\ContractHoursPerDay::__construct(): Argument #2 ($date) must be of type League\\Period\\Datepoint, DateTimeImmutable given

The code calling this is using:
```
foreach ($period->getDatePeriod('1 DAY') as $date) {
  new ContractHoursPerDay($date)
}
```

This works in 4.11 as the getDatePeriod returns a DatePeriod which when iterating over returns a Datepoint object. 
In 4.12 this returns a DateTimeImmutable object. 

For the moment i changed my code to do a Datepoint::create($date). 

#### Expected result

4.12 returns a datepoint from the date period object like 4.11 did. 

#### Actual result

4.12 returns a datetimeImmutable

**Comment by nyamsprod** [comment]
@arendjantetteroo thanks for reporting the issue.

To me this is not really an issue and I will try to explain why. 

- `Period::getDatePeriod` returns a `DatePeriod` instance. 
- `DatePeriod` instance when iterated over only returns `DateTimeInterface` objects. The instance of the object is determined by how the `DatePeriod` start date was instantiated.
- The package **guarantees** that the `DatePeriod` instance returned when iterate over will only return `DateTimeImmutable` instances.
- In version 4 `League\Period\Datepoint` extends `DateTimeImmutable`. (This is no longer the case in version 5)
- if for whatever reason you created a `Period` instance with its start date endpoint being a `League\Period\Datepoint` then the `DatePeriod` instance created by `League\Period\Period::getDatePeriod` will generate `League\Period\Datepoint` instances.

So `Period::getDatePeriod` does honour its contract. The issue here is that you expect that it will  **always** return a `Datepoint` instance which is not true and not part of any contract.

Last but not least the behaviour is made as such so that if you give for instance a `CarbonImmutable` instance the changes are so transparent that Period::getDatePeriod` will generate at the end

**Comment by arendjantetteroo** [comment]
@nyamsprod ok thanks for clearing that up and the fast reply. 

I wrongly assumed that DatePeriod was part of the Period package, while its a php core thing. It's weird this worked in 4.11 and doesn't in 4.12 though. 

I'll use my workaround to create datepoints from any object it returns, this will probably be needed anyway in version 5.
