### ISSUE TITLE
Add ability to associate additional custom data to a Period

### ISSUE THREAD

**Issue by Bibendus83** [thephpleague/period#90]
Hi, it's me again!
I tought it would be nice to add an optional attribute to the Period class so you can associate any data you want to a Period.
I'll explain my use case but I think it may be useful to others.
I need to associate to each of my periods a userId or a roomId, then after I do some Sequence operations like substracts or merges I must be able to retrieve the data back from the resulting Periods in the Sequence.

Do you think it could be a useful feature?

**Comment by nyamsprod** [comment]
@Bibendus83 I understand where you are coming from with this feature and it is on the surface a tempting feature however I have to disagree with its addition because this would make the package becomes break SOLID. 

A `Period` instance is an immutable value object. It is equivalent to a PHP scalar type value. Instead of attaching data to a `Period` instance you should add a `Period` property to your object and perform some operation depending on its value **not the other way around**. If you really want to attach some behaviour to Period ... **maybe** for your use case a `SplObjectStorage` will do but I would argue against such addition into the library for the moment.

**Comment by Bibendus83** [comment]
At the moment I'm already attaching the period class to my objects, however I'm loosing all functionalities from the Sequence class, that's why I tought to this solution.
I tought extending both Period and Sequence classess to add what I need but I think I should redeclare almost everything.

**Comment by strarsis** [comment]
@Bibendus83: You could achieve the same by overriding the comparison functions of the Sequence class so it uses the properties of your custom class.

Appointment class:
- `userId`
- `roomId`
- `period/bookingPeriod/whatever`

`AppointmentSequence` class with overriden comparison functions then can use instances of `Appontment` class.

**Comment by Bibendus83** [comment]
I was thinking about a trait that could be used in objects that contain a sequence so you can apply it to any object you want

**Comment by strarsis** [comment]
.@Bibendus82: This would be nice. I also want to use `Sequence` for getting all the gaps between `Period`s, but there are additional information attached to each `Period`.

**Comment by strarsis** [comment]
@nyamsprod: I noticed that https://github.com/thephpleague/period/pull/100 has been merged.
Does this also contain an implementation or an example for using extending period with custom data?

**Comment by nyamsprod** [comment]
Haven't thought about it this way but it might... with no guarantee or endorsement from me 😉

**Comment by strarsis** [comment]
@nyamsprod: I just noticed that you closed this issue right after the PR has been merged.

**Comment by nyamsprod** [comment]
This was just merge coincidence there's no relation between both actions

**Comment by nyamsprod** [comment]
But indeed the new Chart/Dataset class could serve as a concrete example on how to associate data to a Period class

**Comment by strarsis** [comment]
@nyamsprod: An example, mention, and link in the documentation would be great.

**Comment by nyamsprod** [comment]
@strarsis no because it's purpose is well defined... in the documentation 😉
