### ISSUE TITLE
Create from ISO8601 string

### ISSUE THREAD

**Issue by simoheinonen** [thephpleague/period#91]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    |no

#### Proposal

`__toString()` already exists but there's no (simple) way of converting that back to `Period`

**Comment by nyamsprod** [comment]
@simoheinonen there are none because it is not that simple 😄 . If you look at https://en.wikipedia.org/wiki/ISO_8601#Time_intervals you will understand why coming up with a clear simple implementation of a potential `Period::fromString` is difficul. If you can provide a PR for that then I'll add it without any hesitation.

**Comment by nyamsprod** [comment]
the to/fromISO8601 are merged in the master branch and will be part of the next feature release.

**Comment by simoheinonen** [comment]
Nice! How do you feel about doing the fourth one `Duration only, such as "P1Y2M10DT2H30M", with additional context information` as `Period::createFromDuration('now', 'P1Y2M10DT2H30M');`. Can open a PR if you think that makes sense.

**Comment by nyamsprod** [comment]
@simoheinonen you mean `fromISO8601(string $isoFormat, $context = null);` 🤔  . where context is a datepoint ? 

Maybe this can be done via your PR yes. I'm open to that but keep in mind that partial datepoint will fails because not supported 😉

**Comment by nyamsprod** [comment]
on a second thoughts ... your `Period::createFromDuration` already exists ... its one of the `Period::after` or `Period::before` or `Period::around` one of them already do that 👍  so I don't think it is needed after all

**Comment by simoheinonen** [comment]
I mean adding support to `fromISO8601` for partial datepoint which would then default to use "NOW" as the starting point.

Something like this (didn't test yet): 
```php
if ($separator === null || strpos($isoFormat, $separator) === false) {
    return self::after('now', new DateInterval($isoFormat));
}
```

**Comment by simoheinonen** [comment]
If in the context we know the start date then why wouldn't we just use the start date when creating the period. If we don't then we need to assume the start date to be something or not do anything. Not sure which one makes more sense.

**Comment by nyamsprod** [comment]
> If in the context we know the start date then why wouldn't we just use the start date when creating the period.

that's what the `:before`, `:after`, `:around` named constructors are for

> If we don't then we need to assume the start date to be something or not do anything.

We do nothing is the best solution AKA .. we throw and tell the user that interval only format are not supported or that they need to use the listed named constructor above for better clarity. I hate it when a library assume a default which is a business decision which by nature vary per project/usage.

**Comment by nyamsprod** [comment]
@simoheinonen bad news ... I'm going to revert the master and remove the new fromIso8601 named constructor ... reason being that the current implementation in the master is not handling most of the case after much research turns out that the implementation is really below average. I'd rather remove it for now instead of shipping a subpar product.

Once I've figure out how to improve the implementation I'll resubmit the feature for integration.

Sorry about that

**Comment by nyamsprod** [comment]
this might be visited again when a v5 is planned and in development
